apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: endpoint-tests
  namespace: spring-app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-spring-app
    meta.helm.sh/release-namespace: spring-app
spec:
  metrics:
    - name: endpoint-test
      provider:
        job:
          spec:
            template:
              metadata:
                labels:
                  app: endpoint-tester
              spec:
                securityContext:
                  runAsUser: 0  # Run as root
                containers:
                  - name: curl-container
                    image: curlimages/curl:latest
                    command: ["sh", "-c"]
                    args:
                      - |
                        set -e
                        echo "Updating /etc/hosts..."
                        echo "4.224.90.31 backend-spring-app.com" >> /etc/hosts
                        echo "Updated /etc/hosts with backend-spring-app.com"

                        echo "Checking /etc/hosts..."
                        cat /etc/hosts

                        # Test if the hostname resolves correctly
                        echo "Testing backend-spring-app.com resolution..."
                        resolved_ip=$(getent hosts backend-spring-app.com | awk '{ print $1 }')
                        echo "Resolved IP: $resolved_ip"

                        # Directly test the endpoint with headers
                        echo "Directly testing the endpoint..."
                        endpoint_response=$(curl -fs -H "Accept: application/json" -o response_body.txt -w "%{http_code}" -X GET "http://backend-spring-app.com/spring-app/")
                        endpoint_body=$(<response_body.txt)

                        echo "Endpoint Response Code: $endpoint_response"
                        echo "Endpoint Response Body: $endpoint_body"

                        # Check if the response is empty
                        if [ -z "$endpoint_body" ]; then
                          echo "Received an empty response body from http://backend-spring-app.com/spring-app/"
                        fi

                        # Check the expected responses
                        check_endpoint() {
                          expected_status="$1"
                          expected_response="$2"
                          url="$3"
                          response=$(curl -fs -H "Accept: application/json" -o response_body.txt -w "%{http_code}" -X GET "$url" || echo "Curl failed")
                          body=$(<response_body.txt)

                          echo "Response code: $response"
                          echo "Response body: $body"

                          if [ "$response" != "$expected_status" ]; then
                            echo "Test failed for $url: Expected status '$expected_status' but got '$response'"
                            exit 1  # Fail the job
                          elif [ "$body" != "$expected_response" ]; then
                            echo "Test failed for $url: Expected response '$expected_response' but got '$body'"
                            exit 1  # Fail the job
                          else
                            echo "Test passed for $url: Received status '$response' and body '$body'"
                          fi
                        }

                        echo "Testing additional endpoints..."
                        check_endpoint "200" '{"status":"200","message":"WELCOME"}' "http://backend-spring-app.com/spring-app/"
                        check_endpoint "201" '{"status":"201","message":"CREATED"}' "http://backend-spring-app.com/spring-app/resource-created"
                        check_endpoint "202" '{"status":"202","message":"ACCEPTED"}' "http://backend-spring-app.com/spring-app/resource-accepted"
                        check_endpoint "406" '{"status":"406","message":"NOT_ACCEPTABLE"}' "http://backend-spring-app.com/spring-app/resource-not-acceptable"
                        check_endpoint "501" '{"status":"501","message":"NOT_IMPLEMENTED"}' "http://backend-spring-app.com/spring-app/resource-not-implemented"
                        
                        echo "All tests completed."
                restartPolicy: Never
