apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: endpoint-tests
  namespace: spring-app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-spring-app
    meta.helm.sh/release-namespace: spring-app
spec:
  metrics:
    - name: endpoint-test
      provider:
        job:
          spec:
            template:
              metadata:
                labels:
                  app: endpoint-tester
              spec:
                containers:
                  - securityContext:
                      runAsUser: 0  # Run as root
                  - name: curl-container
                    image: curlimages/curl:latest
                    command: ["sh", "-c"]
                    args:
                      - |
                        set -e

                        # Directly update /etc/hosts
                        echo "Updating /etc/hosts..."
                        echo "4.224.90.31 backend-spring-app.com" >> /etc/hosts

                        echo "Waiting for changes..."
                        sleep 10  # Adjust wait time as necessary

                        echo "Checking /etc/hosts..."
                        cat /etc/hosts

                        echo "Checking DNS resolution for backend-spring-app.com..."
                        nslookup backend-spring-app.com
                        
                        check_endpoint() {
                          expected_status="$1"
                          expected_response="$2"
                          url="$3"
                          response=$(curl -s -o response_body.txt -w "%{http_code}" "$url")
                          body=$(<response_body.txt)

                          if [ "$response" != "$expected_status" ]; then
                            echo "Test failed for $url: Expected status '$expected_status' but got '$response'"
                            exit 1  # Fail the job
                          elif [ "$body" != "$expected_response" ]; then
                            echo "Test failed for $url: Expected response '$expected_response' but got '$body'"
                            exit 1  # Fail the job
                          else
                            echo "Test passed for $url: Received status '$response' and body '$body'"
                          fi
                        }

                        echo "Testing endpoints..."

                        check_endpoint "200" '{"status":"200","message":"WELCOME"}' "http://backend-spring-app.com/spring-app/"
                        check_endpoint "201" '{"status":"201","message":"CREATED"}' "http://backend-spring-app.com/spring-app/resource-created"
                        check_endpoint "202" '{"status":"202","message":"ACCEPTED"}' "http://backend-spring-app.com/spring-app/resource-accepted"
                        check_endpoint "406" '{"status":"406","message":"NOT_ACCEPTABLE"}' "http://backend-spring-app.com/spring-app/resource-not-acceptable"
                        check_endpoint "501" '{"status":"501","message":"NOT_IMPLEMENTED"}' "http://backend-spring-app.com/spring-app/resource-not-implemented"
                        
                        echo "All tests passed successfully."
                restartPolicy: Never
