apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: istio-ingress-analysis
spec:
  metrics:
    - name: request-success-rate
      interval: 1m
      count: 5  # Specify the number of times the analysis should run
      successCondition: result > 0.95
      failureCondition: result < 0.90
      provider:
        prometheus:
          address: https://defaultazuremonitorworkspace-cin-d4e6gnhdc0etbsas.centralindia.prometheus.monitor.azure.com
          query: |
            sum(rate(istio_requests_total{destination_service=~"springboot-app.*", response_code=~"2.."}[1m])) / sum(rate(istio_requests_total{destination_service=~"springboot-app.*"}[1m]))
