apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: endpoint-tests
  namespace: spring-app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-spring-app
    meta.helm.sh/release-namespace: spring-app
spec:
  metrics:
    - name: root-endpoint
      successCondition: result == "WELCOME"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/
          method: GET
          timeoutSeconds: 5
          headers:
            - key: Accept
              value: application/json
    - name: resource-created-endpoint
      successCondition: result == "CREATED"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/resource-created
          method: GET
          timeoutSeconds: 5
          headers:
            - key: Accept
              value: application/json
    - name: resource-accepted-endpoint
      successCondition: result == "ACCEPTED"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/resource-accepted
          method: GET
          timeoutSeconds: 5
          headers:
            - key: Accept
              value: application/json