apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: endpoint-tests
  namespace: spring-app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-spring-app
    meta.helm.sh/release-namespace: spring-app
spec:
  metrics:
    - name: endpoint-test
      #failureLimit: 4
      provider:
        job:
          spec:
            ttlSecondsAfterFinished: 300  # Job will be deleted 5 minutes after finishing
            backoffLimit: 3
            activeDeadlineSeconds: 150  # Set the time in seconds before which the job should not end
            template:
              metadata:
                labels:
                  app: endpoint-tester
              spec:
                securityContext:
                  runAsUser: 0  # Run as root
                containers:
                  - name: curl-container
                    image: curlimages/curl:latest
                    command: ["sh", "-c"]
                    args:
                      - |
                        set -e
                        echo "Updating /etc/hosts..."
                        echo "4.224.90.31 backend-spring-app.com" >> /etc/hosts
                        echo "Updated /etc/hosts with backend-spring-app.com"

                        echo "Checking /etc/hosts..."
                        cat /etc/hosts

                        # Test if the hostname resolves correctly
                        echo "Testing backend-spring-app.com resolution..."
                        resolved_ip=$(getent hosts backend-spring-app.com | awk '{ print $1 }')
                        echo "Resolved IP: $resolved_ip"

                        # Directly test the endpoint with headers
                        echo "Directly testing the endpoint..."
                        endpoint_response=$(curl -fs -H "Accept: application/json" "http://backend-spring-app.com/spring-app/")
                        echo "Endpoint Response: $endpoint_response"

                        # Check if the response is empty
                        if [ -z "$endpoint_response" ]; then
                          echo "Received an empty response body from http://backend-spring-app.com/spring-app/"
                        fi

                        # Check the expected responses
                        check_endpoint() {
                          expected_response="$1"
                          url="$2"

                          # Get the response directly
                          response=$(curl -fs "$url" || echo "Curl failed")

                          echo "Response: $response"

                          # Check if the response matches the expected response
                          if [ "$response" != "$expected_response" ]; then
                            echo "Test failed for $url: Expected response '$expected_response' but got '$response'"
                            exit 1  # Fail the job
                          else
                            echo "Test passed for $url: Received expected response '$response'"
                          fi
                        }

                        echo "Testing additional endpoints..."
                        check_endpoint '{"status":"200","message":"WELCOME"}' "http://backend-spring-app.com/spring-app/"
                        check_endpoint '{"status":"201","message":"CREATED"}' "http://backend-spring-app.com/spring-app/resource-created"
                        check_endpoint '{"status":"202","message":"ACCEPTED"}' "http://backend-spring-app.com/spring-app/resource-accepted"
                        #check_endpoint '{"status":"406","message":"NOT_ACCEPTABLE"}' "http://backend-spring-app.com/spring-app/resource-not-acceptable"
                        #check_endpoint '{"status":"501","message":"NOT_IMPLEMENTED"}' "http://backend-spring-app.com/spring-app/resource-not-implemented"
                      
                        echo "All tests completed."
                restartPolicy: Never