apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: endpoint-tests
  namespace: spring-app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-spring-app
    meta.helm.sh/release-namespace: spring-app
spec:
  metrics:
    - name: root-endpoint
      successCondition: result == "WELCOME"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/
    - name: resource-created-endpoint
      successCondition: result == "CREATED"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/resource-created
    - name: resource-accepted-endpoint
      successCondition: result == "ACCEPTED"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/resource-accepted
    - name: resource-not-acceptable-endpoint
      successCondition: result == "NOT_ACCEPTABLE"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/resource-not-acceptable
    - name: resource-not-implemented-endpoint
      successCondition: result == "NOT_IMPLEMENTED"
      provider:
        web:
          url: http://backend-spring-app.com/spring-app/resource-not-implemented