apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-app.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx  # Use this instead of the annotation
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}
                port:
                  number: {{ $.Values.service.port }}
