apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-app.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.kubernetes.io/ingress.class }}
spec:
  rules:
    - http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}
                port:
                  number: {{ $.Values.service.port }}  # Change this to .Values.service.port if needed
          {{- end }}
