apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-app.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths[0].path }}
            pathType: {{ .Values.ingress.paths[0].pathType }}
            backend:
              service:
                name: {{ .Values.ingress.paths[0].backend.service.name }}
                port:
                  number: {{ .Values.ingress.paths[0].backend.service.port.number }}