apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "spring-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
  annotations:
    redeploy-timestamp: "{{ .Release.Time | toString }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spring-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-app.labels" . | nindent 8 }}
          {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
    spec:
      initContainers:
        - name: init-image
          image: busybox  # A lightweight image for the init container
          command: ['sh', '-c', 'echo "IMAGE_NAME={{ .Values.image.repository }}:{{ .Values.image.tag }}" > /mnt/image-name/image-name.txt']
          volumeMounts:
            - name: image-name
              mountPath: /mnt/image-name
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.port }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['image-name']
          volumeMounts:
            - name: image-name
              mountPath: /mnt/image-name
      volumes:
        - name: image-name
          emptyDir: {}
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: endpoint-tests
        - pause: {}
        - setWeight: 100
