apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "spring-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containers.port }}