apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "spring-app.selectorLabels" . | nindent 4 }}