apiVersion: v2
name: argo-cd
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed.
# The version format is year.month.patchnumber.
# Increment this version number each time changes are made to the application.
# Note that this versioning does not follow Semantic Versioning.
# Instead, it reflects the version the application is using.
# It is recommended to use quotes around the version number.
appVersion: "2024.10.27"

