replicaCount: 2

namespace: argo-cd-spring

releaseName: argo-cd

image:
  repository: "yadnesh082024/github-actions-backend"
  pullPolicy: IfNotPresent
  tag: main-20241025100012

service:
  type: ClusterIP
  port: 80
  #nodePort: 30030

containers:
  port: 8080

podLabels: {}  # Add this if needed to customize pod labels

ingress:
  enabled: true
  hosts:
    - host: argo-cd.backend-spring-app.com
      paths:
        - path: /spring-app
          pathType: Prefix
