name: backend
namespace: argocd
project: default
repoURL: 'https://github.com/yadnesh082024/spring-boot-backend-k8s-manifests.git'
targetRevision: main
path: ./spring-boot-backend-helm-chart
helm:
  valueFiles:
    - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: spring-app
syncPolicy:
  automated:
    prune: true
    selfHeal: true
