apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yadnesh082024/spring-boot-backend-k8s-manifests.git'
    targetRevision: main
    path: ./spring-boot-backend-helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spring-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true