replicaCount: 2

namespace: blueGreen-rollouts-spring

releaseName: blueGreen-rollouts

image:
  repository: "yadnesh082024/github-actions-backend"
  pullPolicy: IfNotPresent
  tag: main-20241024153943

service:
  type: ClusterIP
  port: 80
  #nodePort: 30050


containers:
  port: 8080

podLabels: {}  # Add this if needed to customize pod labels

ingress:
  enabled: true
  hosts:
    - host: blueGreen.rollouts.backend-spring-app.com
      paths:
        - path: /spring-app
          pathType: Prefix
