apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: response-time-analysis
spec:
  metrics:
    - name: average-response-time
      successCondition: result[0] < 0.5
      failureCondition: result[0] >= 0.5
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus-server.prometheus.svc.cluster.local
          query: avg(http_server_requests_seconds_sum{job="rollouts-spring-boot-canary"} / http_server_requests_seconds_count{job="rollouts-spring-boot-canary"})