apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "spring-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spring-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-app.labels" . | nindent 8 }}
          {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.port }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_NAME
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  strategy:
    canary:
      canaryService: {{ include "spring-app.fullname" . }}-canary
      stableService: {{ include "spring-app.fullname" . }}
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: tests
              - templateName: response-time-analysis
        - pause: {duration: 120s}
        - setWeight: 100
