name: Update Dropdown Options

on:
  workflow_dispatch:

jobs:
  update-options:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: yadnesh082024/spring-boot-backend-k8s-manifests
          token: ${{ secrets.GH_PAT_UPDATE_MANIFEST }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub-Actions-CI-Build"
          git config --global user.email "user@gitHubActions.com"

      - name: Find files with 'values' in the name
        id: find_files
        run: |
          files=$(find ./argocd-configs/argocd-app-helm-chart -type f -name '*values*' | sort | uniq)
          files_list=$(echo "$files" | tr '\n' ' ')
          echo "files_list=$files_list" >> $GITHUB_ENV

      - name: Clear existing options and update dropdown options
        run: |
          # Clear existing options
          sed -i '/options:/,/^ *$/d' .github/workflows/argo-application.yml
          # Add the options header back with 2 spaces indentation
          sed -i '/type: choice/a \  options:' .github/workflows/argo-application.yml
          # Add new options with proper indentation
          for file in ${{ env.files_list }}; do
            sed -i "/  options:/a \          - ${file}" .github/workflows/argo-application.yml
          done

      - name: Commit and push changes
        run: |
          git add .github/workflows/argo-application.yml
          git commit -m "Update dropdown options in argo-application workflow"
          git push origin main || echo "Push failed, possibly due to lack of permissions"
