name: Update Dropdown Options

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-options:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: yadnesh082024/spring-boot-backend-k8s-manifests
          token: ${{ secrets.GH_PAT_UPDATE_MANIFEST }}

      - name: Find files with 'values' in the name
        id: find_files
        run: |
          files=$(find ./argocd-configs/argocd-app-helm-chart -type f -name '*values*')
          files_list=$(echo "$files" | tr '\n' ' ')
          echo "files_list=$files_list" >> $GITHUB_ENV

      - name: Update dropdown options
        run: |
          # Initialize options variable
          options=""
          # Loop through each file and format it for the options
          for file in ${{ env.files_list }}; do
            options="${options}          - ${file}\n"
          done

          # Update the workflow file with new options
          sed -i "/options:/a ${options}" .github/workflows/argo-application.yml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/workflows/argo-application.yml
          git commit -m "Update dropdown options in argo-application workflow"
          git push
