name: Update Dropdown Options

on:
  push:
    paths:
      - 'spring-boot-backend-k8s-manifests/argocd-configs/argocd-app-helm-chart/**'

jobs:
  update-dropdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate workflow file
        run: |
          python generate_workflow.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/workflows/manual-trigger.yml
          git commit -m 'Update dropdown options in manual-trigger.yml'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}