name: Update Dropdown Options

on:
  workflow_dispatch:

jobs:
  update-options:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: yadnesh082024/spring-boot-backend-k8s-manifests
          token: ${{ secrets.GH_PAT_UPDATE_MANIFEST }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub-Actions-CI-Build"
          git config --global user.email "user@gitHubActions.com"

      - name: Find files with 'values' in the name
        id: find_files
        run: |
          files=$(find ./argocd-configs/argocd-app-helm-chart -type f -name '*values*' | sort | uniq)
          files_list=$(echo "$files" | tr '\n' ',') # Use comma as delimiter
          echo "files_list=${files_list}" >> $GITHUB_ENV

      - name: Clear existing options and update dropdown options
        run: |
          # Define the path to the workflow files
          workflow_files=(
            '.github/workflows/argo-application.yml'
            '.github/workflows/update-dropdown.yml'
          )
          
          for workflow_file in "${workflow_files[@]}"; do
            # Check if the file exists before attempting to modify it
            if [[ -f "$workflow_file" ]]; then
              # Clear existing options
              sed -i '/options:/,/^ *$/d' "$workflow_file"
              # Add the options header back with 2 spaces indentation
              sed -i '/type: choice/a \  options:' "$workflow_file"
          
              # Convert the comma-separated string back into an array
              IFS=',' read -r -a files_array <<< "${{ env.files_list }}"
              for file in "${files_array[@]}"; do
                # Append new options with correct indentation (4 spaces)
                sed -i "/  options:/a \    - ${file}" "$workflow_file"
              done
            else
              echo "Warning: $workflow_file does not exist and will be skipped."
            fi
          done

      - name: Commit and push changes
        run: |
          git add .github/workflows/*.yml
          git commit -m "Update dropdown options in workflow files" || echo "No changes to commit"
          git push origin main || echo "Push failed, possibly due to lack of permissions"
