name: Update Dropdown Options

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-options:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find files with 'values' in the name
        id: find_files
        run: |
          files=$(find ./argocd-configs/argocd-app-helm-chart -type f -name '*values*' | tr '\n' ' ')
          echo "files=$files" >> $GITHUB_ENV

      - name: Update dropdown options
        run: |
          # Convert the found files into the required format for the options
          options=$(echo "${{ env.files }}" | tr ' ' '\n' | sed 's/^/          - /')

          # Update the workflow file with new options
          sed -i "s/options:\n          - /options:\n${options}/" .github/workflows/configure-app-with-argo-cd.yml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/workflows/configure-app-with-argo-cd.yml
          git commit -m "Update dropdown options in configure-app-with-argo-cd workflow"
          git push
